### ISSUE TITLE
Remove monolithic compiled bootstrap javascript library

### ISSUE THREAD

**Issue by zipymonkey** [psu-libraries/psulib_base#45]
Ideally, we'd include only javascript that is actively being used on every page.   Javascript that is not needed globally should be included a specific library that is then included only when needed. An example of this is are the carousel library.

## Task

- [ ] Update mix command to copy individual javascript files from node_modules/bootstrap
- [ ] Add individual js files to targeted libraries (accordion, carousel, etc).
- [ ] Add remaining javascript to global_styles library

**Comment by zipymonkey** [comment]
This was already done the `/js/psul-bootstrap.js` file pulls in only js that is used on all pages.
