### ISSUE TITLE
Update link colors

### ISSUE THREAD

**Issue by zipymonkey** [psu-libraries/psulib_base#46]
The link colors in the header, body and footer are not correct. These should be updated to match the link colors in the brand guidelines.  This will ensure that the links accessible. 

# Tasks

- [x] Override bootstrap link variables
- [x] Add any addition styles to handle menu links in header
- [x] Add any addition styles to handle menu links and other links in the footer.
