### ISSUE TITLE
Add additional components for hershey site

### ISSUE THREAD

**Issue by zipymonkey** [psu-libraries/psulib_base#50]
We need additional items for the Hershey site.

## Tasks

- [x] Main menu not clickable
- [x] accordion on page: /about/maps-directions
- [x] carousel on page: /about/news-events
- [x] views filter: /tech-help/available-equipment
- [ ] page: /tech-help/available-equipment/charging-cables

## Related Items

- https://github.com/psu-libraries/psulib_base/issues/41
- https://github.com/psu-libraries/hershey/pull/177

**Comment by zipymonkey** [comment]
Menu is related to the Popper library. 

`Uncaught TypeError: i.createPopper is not a function`

**Comment by zipymonkey** [comment]
List group and image-fluid classes are missing.  Re-opening this ticket.
