### ISSUE TITLE
Add styles for breadcrumbs

### ISSUE THREAD

**Issue by zipymonkey** [psu-libraries/psulib_base#54]
Need to adjust the breadcrumb styles.  The breadcrumbs are defined in the [components/breadcrumbs](https://github.com/psu-libraries/psulib_base/tree/main/components/breadcrumbs)

## Styles
Based on https://dev--64821f7a7ea081d31324f929.chromatic.com/?path=/story/core-composite-navigation-breadcrumbs--default   The bootstrap breadcrumb documentation is here: https://getbootstrap.com/docs/5.3/components/breadcrumb/#dividers

* Font: `Roboto_Condensed`
* Font Size: `$font-size-sm`
* Separator: `/`
* Link color: (standard link color)

## Tasks

- [ ] Adjust bootstrap styles 
- [ ] Update breadcrumbs to show current page.  This is probably something that needs to be added to the template/psul-web projects.  
- [ ] Remove `@import "~bootstrap/scss/breadcrumb";` from `styles.scss`

Alternative styles could be: https://developers.outreach.psu.edu/form-styles/?p=organisms-breadcrumbs

**Comment by zipymonkey** [comment]
@schwent I think this is complete.  Is it OK to close this?

**Comment by zipymonkey** [comment]
Re-opened this ticket so we can get the current page text added to the breadcrumbs.
