### ISSUE TITLE
SDC: Port Accordion component to base theme

### ISSUE THREAD

**Issue by zipymonkey** [psu-libraries/psulib_base#62]
Add a new SDC component for accordions. 

## Tasks

- [x] Port accordion component from psul_theme.  Clean up styles component as necessary. 
- [x] Remove accordion library from .info file
- [x] Remove accordion.scss stylesheet

**Comment by schwent** [comment]
@zipymonkey - want me to try this one?

**Comment by zipymonkey** [comment]
Sure.  We don't currently have anything that implements this so it might be a bit tricky to verify.

**Comment by zipymonkey** [comment]
See #250.  If the SDC is created there we can port that into the psulib_base module.

**Comment by zipymonkey** [comment]
The SDC was created in psul_theme.  The component needs some work but it is a good starting place.
