### ISSUE TITLE
Add pager component

### ISSUE THREAD

**Issue by zipymonkey** [psu-libraries/psulib_base#65]
Add a new SDC component for pagers.

## Tasks

- [ ] Add new pager component
- [ ] Remove pagination library from .info file
- [ ] Remove pagination.scss stylesheet
- [ ] Use new component in ./psulib_base/templates/navigation/pager.html.twig

## Links
* Example component: https://git.drupalcode.org/project/radix/-/tree/6.0.x/components/pagination?ref_type=heads
*

**Comment by zipymonkey** [comment]
@schwent I created a issues for the Pager component.  We can step through the process for getting this setup on Monday.
