### ISSUE TITLE
Homepage tabbed "Find" component

### ISSUE THREAD

**Issue by zipymonkey** [psu-libraries/psulib_base#67]
This needs a SDC and a configurable block.

## Tasks

- [x] psu-libraries/psul-web#262
- [x] psu-libraries/psul-web#270
- [x] psu-libraries/psul-web#303
- [x] Port [homepage_features](https://libraries.psu.edu/admin/structure/views/view/homepage_features/edit/page_1) view.  
- [x] Add templates and styles for the [homepage_features](https://github.com/psu-libraries/ul-web/tree/main/vendor/custom/themes/f5_psul/templates/homepage-features).  Include the Find component block in the view template.

## Examples

- [UL](https://libraries.psu.edu/)
- [Hershey](https://hershey.libraries.psu.edu/)

**Comment by zipymonkey** [comment]
There are a number of components needed to build the Find component

**Comment by zipymonkey** [comment]
There is an A-Z views area plugin that has the start of this.  I would make sense to split the Glossary A-Z into a SDC so it can be used in multiple places.
